pipeline:
  rspec:
    image: ruby:alpine
    commands:
      - bundle install --path vendor/bundle
      - bundle exec rspec
  slack:
    image: plugins/slack
    channel: release
    secrets: [ slack_webhook ]
    when:
      status: [ success, failure ]
